#
# Marlin Firmware
# PlatformIO Configuration File
#

####################################
#
# HAL/MFL GD32 Environments
#
####################################

[gd32_base]
platform            = https://github.com/bmourit/platform-mfl/archive/refs/tags/V1.0.4.zip
board_build.core    = gd32
build_src_filter    = ${common.default_src_filter} +<src/HAL/GD32_MFL> +<src/HAL/shared/backtrace>
build_unflags       = -std=gnu++11 -std=gnu++14 -std=gnu++17
build_flags         = -std=gnu++23
                      -DARDUINO_ARCH_MFL
                      -DPLATFORM_M997_SUPPORT
					  -DGD32F303RE
                      -DTIMER_IRQ_PRIORITY=12
                      -DADC_RESOLUTION=12
                      -DCORE_DEBUG
                      -Wno-deprecated-declarations
extra_scripts       = ${common.extra_scripts}
lib_deps            = ${common.lib_deps}
                      marlinfirmware/U8glib-HAL@0.5.5

#
# Creality (GD32F303RE)
#
[env:GD32F303RE_creality_mfl]
extends                     = gd32_base
board                       = mfl_creality_v4
board_build.offset          = 0x7000
board_upload.offset_address = 0x08007000
board_build.rename          = firmware-{time}.bin
build_flags                 = ${gd32_base.build_flags}
                              -DMCU_GD32F303RE
                              -DGD32F303RE
                              -DTIMER_TONE=2
                              -DSS_TIMER=3
                              -DTIMER_SERVO=4
                              -DTRANSFER_CLOCK_DIV=8
							  #-D SOFTWARE_SERIAL_STM32_API_COMPATIBILITY=1
							  #-D PANIC_ENABLE=1
extra_scripts               = ${gd32_base.extra_scripts}
                              buildroot/share/PlatformIO/scripts/offset_and_rename.py
monitor_speed               = 115200

#
# Creality (GD32F303RE)
#
[env:GD32F303RE_xXHenneBXx_mfl]
extends                     = common_stm32
board                       = genericGD32F303RE
board_build.offset          = 0x7000
board_upload.offset_address = 0x08007000
board_build.rename          = firmware-update-{time}.bin
build_flags                 = ${STM32F103Rx_creality.build_flags}
							  ${gd32_base.build_flags}
							  #${common_STM32F103RC_variant.build_flags}
							  -DARDUINO_ARCH_MFL
                              -DMCU_GD32F303RE
                              -DGD32F303RE
                              -DTIMER_TONE=2
                              -DSS_TIMER=3
                              -DTIMER_SERVO=4
                              -DTRANSFER_CLOCK_DIV=8
							  -D SOFTWARE_SERIAL_STM32_API_COMPATIBILITY=1
							  -D PANIC_ENABLE=1
							  -DHAL_PCD_MODULE_ENABLED
							  -DDISABLE_GENERIC_SERIALUSB
							  -DHAL_UART_MODULE_ENABLED
extra_scripts               = ${gd32_base.extra_scripts}
                              buildroot/share/PlatformIO/scripts/offset_and_rename.py
monitor_speed               = 115200

#
# Aquila v1.0.1 (GD32F103RC)
#
[env:GD32F103RC_aquila_mfl]
extends                     = gd32_base
board                       = mfl_aquila
board_build.offset          = 0x7000
board_upload.offset_address = 0x08007000
board_build.rename          = firmware-{time}.bin
build_flags                 = ${gd32_base.build_flags}
                              -DMCU_GD32F103RC
                              -DGD32F103RC
                              -DTIMER_TONE=2
                              -DSS_TIMER=3
                              -DTIMER_SERVO=4
                              -DTRANSFER_CLOCK_DIV=8
extra_scripts               = ${gd32_base.extra_scripts}
                              buildroot/share/PlatformIO/scripts/offset_and_rename.py
monitor_speed               = 115200
