#
# Marlin Firmware
# PlatformIO Configuration File
#

#################################
#
# HC32F460 Architecture with unified HC32 HAL
#
# Naming Example: HC32F460JEUA
#
# |- Xiaohua Semiconductor
# |  |- CPU bit width (32: 32-bit)
# |  |  |- Product Type (F: Universal MCU)
# |  |  | |- Core Type (4: Cortex-M4)
# |  |  | | |- Performance (6: High Performance)
# |  |  | | | |- Configuration (0: Configuration 1)
# |  |  | | | | |- Pin Count (J: 48, K: 60/64, P: 100)
# |  |  | | | | | |- Flash Capacity (C: 256KB, E: 512KB)
# |  |  | | | | | | |- Package (T: LQFP, U: QFN, H:VFBGA)
# |  |  | | | | | | | |- Temperature range (A: -40-85°C, B: -40-105°C)
# HC 32 F 4 6 0 J E U A
#
#################################

#
# Base Environment for all HC32F460 variants
#
[HC32F460_base]
platform          = https://github.com/classicrocker883/platform-hc32f46x/archive/main.zip
platform_packages = framework-hc32f46x-ddl@https://github.com/classicrocker883/framework-hc32f46x-ddl/archive/main.zip
                    framework-arduino-hc32f46x@https://github.com/classicrocker883/framework-arduino-hc32f46x/archive/main.zip
board             = generic_hc32f460
build_src_filter  = ${common.default_src_filter} +<src/HAL/HC32> +<src/HAL/shared/backtrace>
build_type        = release
build_flags       = -D ARDUINO_ARCH_HC32=1
                    -D PLATFORM_M997_SUPPORT=1          # Enable M997 command
                                                        # NOTE: DDL and Arduino debug mode are
                                                        # Automatically enabled with MARLIN_DEV_MODE
                    -D REDIRECT_PRINTF_TO_SERIAL=1      # Redirect core-provided printf to host serial
                    -D F_CPU=F_HCLK                     # F_CPU is F_HCLK, as that's the main CPU core's clock.
                    -D USART_AUTO_CLKDIV_OS_CONFIG=1    # Enable support for Usart Clock Divider / Oversampling auto config

                   # DDL / Arduino Configuration
                    -D DISABLE_SERIAL_GLOBALS=1         # Disable global Serial objects, we use our own
                   #-D CORE_DISABLE_FAULT_HANDLER=1     # Disable arduino core fault handler (we use our own) if POSTMORTEM_DEBUGGING is enabled
                   #-D USART_RX_DMA_SUPPORT=1           # Enable core option when SERIAL_DMA is enabled
                    -D SOFTWARE_SERIAL_STM32_API_COMPATIBILITY=1
                                                        # SoftwareSerial uses STM32duino API compatibility mode
                   #-D SERIAL_BUFFER_SIZE=256           # Increase the size of the Usart buffers (both RX and TX)

                   # DDL / Arduino Debug Options
                   #-D __DEBUG=1                        # Force DDL debug mode
                   #-D __CORE_DEBUG=1                   # Force Arduino core debug mode
                    -D PANIC_ENABLE=1                   # Enable custom panic handlers (in MinSerial)

                   # Options to reduce debug mode footprint (-16K; messages are less verbose)
                    -D __DEBUG_SHORT_FILENAMES=1        # Use short filenames in DDL debug output
                    -D __PANIC_SHORT_FILENAMES=1        # Use short filenames in core panic output
                    -D __OMIT_PANIC_MESSAGE=1           # Omit panic messages in core panic output

# HC32 app configuration file
# board_build.app_config = Marlin/src/HAL/HC32/app_config.h

# Drivers and Middleware required by the HC32 HAL
board_build.ddl.ots    = true
board_build.ddl.sdioc  = true
board_build.ddl.wdt    = true
board_build.ddl.timer0 = true
board_build.mw.sd_card = true

# Extra build flags
board_build.flags.common = -g3                   # Force emit debug symbols to elf. This does not affect the final binary size
                           -fno-signed-char      # Force unsigned char. This is required for meatpack to work

# Additional flags to reduce binary size
board_build.flags.cpp = -fno-threadsafe-statics  # Disable thread-safe statics (only one core anyway)
                        -fno-exceptions          # Disable exceptions (not used by Marlin)
                        -fno-rtti                # Disable RTTI (not used by Marlin)

#
# Base HC32F460xCxx (256K Flash)
#
[HC32F460C_base]
extends = HC32F460_base
board_upload.maximum_size = 262144

#
# Base HC32F460xExx (512K Flash)
#
[HC32F460E_base]
extends = HC32F460_base
board_upload.maximum_size = 524288

#
# Voxelab Aquila V1.0.0/V1.0.1/V1.0.2/V1.0.3 as found in the Voxelab Aquila X2 & C2
#
[HC32F460C_aquila]
extends = HC32F460C_base
board_upload.offset_address = 0xC000  # Bootloader start address, as logged by the bootloader on boot
board_build.boot_mode = primary       # Save ~1.4k of flash by compiling as secondary firmware (no ICG)

#
# Creality Ender 2 Pro v2.4.S4_170 (HC32f460kcta) (256K Flash, 192K RAM).
#
[env:HC32F460C_e2p24s4]
extends = HC32F460C_base
board_upload.offset_address = 0x8000

#
# For use with DWIN LCD
#
[env:HC32F460C_aquila_101]
extends = HC32F460C_aquila
board_build.ddl.timera = false
board_build.ddl.i2c    = true

#
# For use with CR10_STOCKDISPLAY
#
[env:HC32F460C_aquila_C2]
extends = HC32F460C_aquila
board_build.ddl.timera = true
board_build.ddl.i2c    = false

# OpenHC32Boot (256K Flash).
# This can be used with any HC32F460C printer, provided it has OpenHC32Boot installed.
# see https://github.com/shadow578/OpenHC32Boot for more information
#
[env:HC32F460C_openhc32boot]
extends = HC32F460C_base
board_upload.offset_address = 0x4000
board_build.boot_mode = secondary
build_flags =
  ${HC32F460C_base.build_flags}
  -D CORE_DONT_RESTORE_DEFAULT_CLOCKS=1  # OpenHC32Boot doesn't mess with the clock settings, so we can skip clock restore in the core

#
# OpenHC32Boot (512K Flash)
#
[env:HC32F460E_openhc32boot]
extends = HC32F460E_base
board_upload.offset_address = 0x4000
board_build.boot_mode = secondary
build_flags =
  ${HC32F460E_base.build_flags}
  -D CORE_DONT_RESTORE_DEFAULT_CLOCKS=1
